/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Hide Toolbar",
  "description": "The toolbar is hidden by default and will automatically appear when you hover nearby. You may also choose to lock it in place for persistent display.",
  "tags": ["new","recommended"],
  "credits": [
    {
      "name": "KOSHINO",
      "link": "https://space.bilibili.com/520948922"
    }
  ],
  "enabledByDefault": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ]
};
export default manifest;
