/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Show FPS",
  "description": "Show stage FPS at top of stage",
  "tags": ["new","recommended"],
  "credits": [
    {
      "name": "KOSHINO",
      "link": "https://github.com/KOSHINOawa"
    }
  ],
  "enabledByDefault": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ]
};
export default manifest;
