name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - run: npm install --ver #Change from "npm ci" to "npm install --ver" because it can't work.
    - run: npm run build
    - run: npm run test:unit
