name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install Dependencies
      run: npm install --ignore-scripts --legacy-peer-deps

    - name: Build scratch-blocks manually
      run: |
        cd node_modules/scratch-blocks
        
        npm install --no-save google-closure-compiler java
        
        export PATH=$(npm bin):$PATH
        
        node universal-python.js build.py
        
    - name: Build GUI
      run: |
        npm run build
        
    - name: Run Tests
      run: npm run test:unit